export const CREATE_NTF_SUCCESS = 'CREATE_NTF_SUCCESS';
export const FETCH_NTFS_SUCCESS = 'FETCH_NTFS_SUCCESS';
export const CLEAR_NTFS_SUCCESS = 'CLEAR_NTFS_SUCCESS';
export const CREATE_NTF_FAILURE = 'CREATE_NTF_FAILURE'
export const FETCH_NTF_BY_TIME_SUCCESS = 'FETCH_NTF_BY_TIME_SUCCESS';
